[deps]
ClassicalSpinMonteCarlo = "f948d270-e492-46ef-bc0b-5a70a63c41c9"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
